version: "3"

services:
  app:
      build: .
      ports:
          - "3000:3000"
      volumes:
          - .:/application
      depends_on:
          - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: asgard
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: priston_production
    ports:
      - "5050:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: pgadmin

volumes:
  postgres:
